name: trend_invest_app_new
description: "A new Flutter project."
publish_to: 'none' # Private package

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Flutter 3.24 ile uyumlu sürümler
  path_provider: 2.0.15
  shared_preferences: 2.1.1
  http: ^1.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.1.11
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - img/
